<select name="COD_Tribunal" class="form-control">
    <option value="0">Todos.</option>
    <option value="2">1º Juzgado de Letras de Arica                     </option>
    <option value="3">2º Juzgado de Letras de Arica                     </option>
    <option value="4">3º Juzgado de Letras de Arica                     </option>
    <option value="5">3º Juzgado de Letras de Arica Ex 4º               </option>
    <option value="1400">1º Juzgado De Letras de Arica ex 4°               </option>
    <option value="1401">2º Juzgado De Letras de Arica ex 4°               </option>
    <option value="6">Juzgado de Letras y Gar. Pozo Almonte             </option>
    <option value="9">1º Juzgado de Letras de Iquique                   </option>
    <option value="10">2º Juzgado de Letras de Iquique                   </option>
    <option value="11">3º Juzgado de Letras de Iquique                   </option>
    <option value="13">Juzgado de Letras Tocopilla                       </option>
    <option value="14">Juzgado de Letras y Gar.de Maria Elena            </option>
    <option value="16">1º Juzgado de Letras de Calama                    </option>
    <option value="17">2º Juzgado de Letras de Calama                    </option>
    <option value="26">Juzgado de Letras y Gar. de Taltal                </option>
    <option value="658">3º Juzgado de Letras de Calama                    </option>
    <option value="1041">1º Juzgado de Letras Civil de Antofagasta         </option>
    <option value="1042">2º Juzgado de Letras Civil de Antofagasta         </option>
    <option value="1043">3º Juzgado de Letras Civil de Antofagasta         </option>
    <option value="1044">4º Juzgado de Letras Civil de Antofagasta         </option>
    <option value="27">Juzgado de Letras y Gar. de Chañaral              </option>
    <option value="29">Juzgado de Letras de Diego de Almagro             </option>
    <option value="31">1º Juzgado de Letras de Copiapó                   </option>
    <option value="32">2º Juzgado de Letras de Copiapó                   </option>
    <option value="33">3º Juzgado de Letras de Copiapó                   </option>
    <option value="34">Juzgado de Letras y Gar.de Freirina               </option>
    <option value="36">1º Juzgado de Letras de Vallenar                  </option>
    <option value="37">2º Juzgado de Letras de Vallenar                  </option>
    <option value="386">Juzgado de Letras y Gar.de Caldera                </option>
    <option value="926">4º Juzgado de Letras de Copiapó                   </option>
    <option value="40">1º Juzgado de Letras de la Serena                 </option>
    <option value="41">2º Juzgado de Letras de la Serena                 </option>
    <option value="42">3º Juzgado de Letras de la Serena                 </option>
    <option value="43">1º Juzgado de Letras de Coquimbo                  </option>
    <option value="44">2º Juzgado de Letras de Coquimbo                  </option>
    <option value="45">3º Juzgado de Letras de Coquimbo                  </option>
    <option value="46">Juzgado de Letras de Vicuña                       </option>
    <option value="47">Juzgado de letras y garantia de Andacollo         </option>
    <option value="48">1º Juzgado de Letras de Ovalle                    </option>
    <option value="49">2º Juzgado de Letras de Ovalle                    </option>
    <option value="50">3º Juzgado de Letras de Ovalle                    </option>
    <option value="51">Juzgado de Letras y Gar.de Combarbalá             </option>
    <option value="52">Juzgado de Letras de Illapel                      </option>
    <option value="53">Juzgado de Letras y Gar. de los Vilos             </option>
    <option value="54">3º Juzgado Civil de Valparaiso                    </option>
    <option value="55">2º Juzgado Civil de Valparaiso                    </option>
    <option value="56">1º Juzgado Civil de Valparaiso                    </option>
    <option value="57">1º Juzgado Civil de Viña del Mar                  </option>
    <option value="58">2º Juzgado Civil de Viña del Mar                  </option>
    <option value="59">4º Juzgado Civil de Valparaiso                    </option>
    <option value="60">5º Juzgado Civil de Valparaiso                    </option>
    <option value="61">3º Juzgado Civil de Viña del Mar                  </option>
    <option value="83">1º Juzgado de Letras de Quilpue                   </option>
    <option value="84">2º Juzgado de Letras de Quilpue                   </option>
    <option value="85">Juzgado de Letras de Villa Alemana                </option>
    <option value="86">Juzgado de Letras de Casablanca                   </option>
    <option value="87">Juzgado de Letras de La Ligua                     </option>
    <option value="88">Juzgado de Letras y Gar. de Petorca               </option>
    <option value="89">1º Juzgado de Letras de Los Andes                 </option>
    <option value="90">2º Juzgado de Letras de Los Andes                 </option>
    <option value="92">1º Juzgado de Letras de San Felipe                </option>
    <option value="93">1º Juzgado de Letras de San Felipe Ex 2º          </option>
    <option value="94">Juzgado de Letras y Gar.de Putaendo               </option>
    <option value="96">1º Juzgado de Letras de Quillota                  </option>
    <option value="97">2º Juzgado de Letras de Quillota                  </option>
    <option value="98">Juzgado de Letras de La Calera                    </option>
    <option value="99">Juzgado de Letras de Limache                      </option>
    <option value="101">1º Juzgado de Letras de San Antonio               </option>
    <option value="102">2º Juzgado de Letras de San Antonio               </option>
    <option value="103">Juzgado de Letras y Gar. de Isla de Pascua        </option>
    <option value="660">Juzgado de Letras y Gar.de Quintero               </option>
    <option value="110">1º Juzgado Civil de Rancagua                      </option>
    <option value="969">2º Juzgado Civil de Rancagua                      </option>
    <option value="111">1º Juzgado de Letras de Rengo                     </option>
    <option value="113">Juzgado de Letras de San Vicente de Tagua Tagua   </option>
    <option value="114">1º Juzgado de Letras y Gar.de Peumo               </option>
    <option value="115">1º Juzgado de Letras de San Fernando              </option>
    <option value="116">2º Juzgado de Letras de San Fernando              </option>
    <option value="117">1º Juzgado de Letras de Santa Cruz                </option>
    <option value="118">1º Juzgado De Letras De Santa Cruz Ex 2°          </option>
    <option value="119">Juzgado de Letras y Gar.de Pichilemu              </option>
    <option value="1150">Juzgado de Letras y Gar.de Litueche               </option>
    <option value="1151">Juzgado de Letras y Gar.de Peralillo              </option>
    <option value="122">1º Juzgado de Letras de Talca                     </option>
    <option value="123">2º Juzgado de Letras de Talca                     </option>
    <option value="124">3º Juzgado de Letras de Talca                     </option>
    <option value="125">4º Juzgado de Letras de Talca                     </option>
    <option value="126">Juzgado de Letras de Constitución                 </option>
    <option value="127">Juzgado De Letras Y Gar. de Curepto               </option>
    <option value="129">1º Juzgado de Letras de Curico                    </option>
    <option value="130">2º Juzgado de Letras de Curico                    </option>
    <option value="131">2º Juzgado de Letras de Curico Ex 3º              </option>
    <option value="132">Juzgado De Letras Y Gar. de Licanten              </option>
    <option value="133">Juzgado de Letras de Molina                       </option>
    <option value="135">1º Juzgado de Letras de Linares                   </option>
    <option value="136">2º Juzgado de Letras de Linares                   </option>
    <option value="138">Juzgado de Letras de San Javier                   </option>
    <option value="139">Juzgado de Letras de Cauquenes                    </option>
    <option value="140">Juzgado de Letras y Gar. de Chanco                </option>
    <option value="141">Juzgado de Letras de Parral                       </option>
    <option value="145">1º Juzgado Civil de Chillan                       </option>
    <option value="146">2º Juzgado Civil de Chillan                       </option>
    <option value="147">1º Juzgado de Letras de San Carlos                </option>
    <option value="149">Juzgado de Letras de Yungay                       </option>
    <option value="150">Juzgado de Letras y Gar. de Bulnes                </option>
    <option value="151">Juzgado de Letras y Gar.de Coelemu                </option>
    <option value="152">Juzgado de Letras y Gar.de Quirihue               </option>
    <option value="154">1º Juzgado de Letras de Los Angeles               </option>
    <option value="155">2º Juzgado de Letras de Los Angeles               </option>
    <option value="156">2° Juzgado de Letras de Los Angeles ex 3°         </option>
    <option value="157">Juzgado de Letras y Gar. de Mulchen               </option>
    <option value="158">Juzgado de Letras y Gar.de Nacimiento             </option>
    <option value="159">Juzgado de Letras y Gar.de Laja                   </option>
    <option value="160">Juzgado de Letras y Gar.de Yumbel                 </option>
    <option value="161">1º Juzgado Civil de Concepción                    </option>
    <option value="162">2º Juzgado Civil de Concepción                    </option>
    <option value="163">3º Juzgado Civil de Concepción                    </option>
    <option value="179">1º Juzgado Civil de Talcahuano                    </option>
    <option value="180">2º Juzgado Civil de Talcahuano                    </option>
    <option value="187">Juzgado de Letras de Tome                         </option>
    <option value="188">Juzgado de Letras y Gar.de Florida                </option>
    <option value="189">Juzgado de Letras y Gar.de Santa Juana            </option>
    <option value="190">Juzgado de Letras y Gar. de Lota                  </option>
    <option value="191">1º Juzgado de Letras de Coronel                   </option>
    <option value="192">2º Juzgado de Letras de Coronel                   </option>
    <option value="193">Juzgado de Letras y Gar.de Lebu                   </option>
    <option value="194">Juzgado de Letras de Arauco                       </option>
    <option value="195">Juzgado de Letras y Gar.de Curanilahue            </option>
    <option value="196">Juzgado de Letras de Cañete                       </option>
    <option value="385">Juzgado de Letras y Gar. Santa Barbara            </option>
    <option value="1152">Juzgado de Letras y Gar.de Cabrero                </option>
    <option value="197">1º Juzgado Civil de Temuco                        </option>
    <option value="198">2º Juzgado Civil de Temuco                        </option>
    <option value="204">Juzgado de Letras de Angol                        </option>
    <option value="206">Juzgado de Letras y Gar.de Collipulli             </option>
    <option value="207">Juzgado de Letras y Gar.de Traiguen               </option>
    <option value="208">Juzgado de Letras de Victoria                     </option>
    <option value="209">Juzgado de Letras y Gar.de Curacautin             </option>
    <option value="210">Juzgado de Letras Loncoche                        </option>
    <option value="211">Juzgado de Letras de Pitrufquen                   </option>
    <option value="212">Juzgado de Letras de Villarrica                   </option>
    <option value="213">Juzgado de Letras de Nueva Imperial               </option>
    <option value="214">Juzgado de Letras y Gar.de Pucon                  </option>
    <option value="215">Juzgado de Letras de Lautaro                      </option>
    <option value="216">Juzgado de Letras y Gar.de Carahue                </option>
    <option value="406">3º Juzgado Civil de Temuco                        </option>
    <option value="946">Juzgado de Letras y Gar.de Tolten                 </option>
    <option value="947">Juzgado de Letras y Gar.de Puren                  </option>
    <option value="220">1º Juzgado Civil de Valdivia                      </option>
    <option value="221">2º Juzgado Civil de Valdivia                      </option>
    <option value="222">Juzgado de Letras de Mariquina                    </option>
    <option value="223">Juzgado de Letras y Gar.de Paillaco               </option>
    <option value="224">Juzgado de Letras Los Lagos                       </option>
    <option value="225">Juzgado de Letras y Gar. de Panguipulli           </option>
    <option value="226">Juzgado de Letras y Gar.de la Union               </option>
    <option value="227">Juzgado de Letras y Gar.de Rio Bueno              </option>
    <option value="229">1º Juzgado de Letras de Osorno                    </option>
    <option value="230">2º Juzgado de Letras de Osorno                    </option>
    <option value="233">Juzgado de Letras de Rio Negro                    </option>
    <option value="237">1º Juzgado Civil de Puerto Montt                  </option>
    <option value="238">Juzgado de Letras de Puerto Varas                 </option>
    <option value="240">Juzgado de Letras y Gar.de Calbuco                </option>
    <option value="241">Juzgado de Letras y Gar. de Maullin               </option>
    <option value="242">Juzgado de Letras de Castro                       </option>
    <option value="243">Juzgado de Letras de Ancud                        </option>
    <option value="244">Juzgado de Letras y Garantia de Achao             </option>
    <option value="245">Juzgado de Letras y Gar. de Chaiten               </option>
    <option value="659">Juzgado de Letras y Gar. de Los Muermos           </option>
    <option value="662">Juzgado de Letras y Gar. de Quellon               </option>
    <option value="1012">2º Juzgado Civil de Puerto Montt                  </option>
    <option value="1013">Juzgado de Letras y Gar. de Hualaihue             </option>
    <option value="246">1º Juzgado de Letras de Coyhaique                 </option>
    <option value="247">1º Juzgado de Letras de Coyhaique Ex 2º           </option>
    <option value="248">Juzgado de Letras y Gar.de pto.Aysen              </option>
    <option value="249">Juzgado de Letras y Gar.de Chile Chico            </option>
    <option value="250">Juzgado de Letras y Gar.de Cochrane               </option>
    <option value="996">Juzgado de Letras y Gar.de Puerto Cisnes          </option>
    <option value="253">1º Juzgado de Letras de Punta Arenas              </option>
    <option value="254">2º Juzgado de Letras de Punta Arenas              </option>
    <option value="255">3º Juzgado de Letras de Punta Arenas              </option>
    <option value="257">Juzgado de Letras y Gar. de Puerto Natales        </option>
    <option value="258">Juzgado de Letras y Gar.de Porvenir               </option>
    <option value="259">1º Juzgado Civil de Santiago                      </option>
    <option value="260">2º Juzgado Civil de Santiago                      </option>
    <option value="261">3º Juzgado Civil de Santiago                      </option>
    <option value="262">4º Juzgado Civil de Santiago                      </option>
    <option value="263">5º Juzgado Civil de Santiago                      </option>
    <option value="264">6º Juzgado Civil de Santiago                      </option>
    <option value="265">7º Juzgado Civil de Santiago                      </option>
    <option value="266">8º Juzgado Civil de Santiago                      </option>
    <option value="267">9º Juzgado Civil de Santiago                      </option>
    <option value="268">10º Juzgado Civil de Santiago                     </option>
    <option value="269">11º Juzgado Civil de Santiago                     </option>
    <option value="270">12º Juzgado Civil de Santiago                     </option>
    <option value="271">13º Juzgado Civil de Santiago                     </option>
    <option value="272">14º Juzgado Civil de Santiago                     </option>
    <option value="273">15º Juzgado Civil de Santiago                     </option>
    <option value="274">16º Juzgado Civil de Santiago                     </option>
    <option value="275">17º Juzgado Civil de Santiago                     </option>
    <option value="276">18º Juzgado Civil de Santiago                     </option>
    <option value="277">19º Juzgado Civil de Santiago                     </option>
    <option value="278">20º Juzgado Civil de Santiago                     </option>
    <option value="279">21º Juzgado Civil de Santiago                     </option>
    <option value="280">22º Juzgado Civil de Santiago                     </option>
    <option value="281">23º Juzgado Civil de Santiago                     </option>
    <option value="282">24º Juzgado Civil de Santiago                     </option>
    <option value="283">25º Juzgado Civil de Santiago                     </option>
    <option value="284">26º Juzgado Civil de Santiago                     </option>
    <option value="285">27º Juzgado Civil de Santiago                     </option>
    <option value="286">28º Juzgado Civil de Santiago                     </option>
    <option value="287">29º Juzgado Civil de Santiago                     </option>
    <option value="288">30º Juzgado Civil de Santiago                     </option>
    <option value="387">Juzgado de Letras de Colina                       </option>
    <option value="9013">Juzgado Civil Prueba                             </option>
    <option value="343">1º Juzgado Civil de San Miguel                    </option>
    <option value="344">2º Juzgado Civil de San Miguel                    </option>
    <option value="345">3º Juzgado Civil de San Miguel                    </option>
    <option value="364">1º Juzgado Civil de Puente Alto                   </option>
    <option value="373">1º Juzgado De Letras De Talagante                 </option>
    <option value="374">2º Juzgado De Letras De Talagante                 </option>
    <option value="375">1º Juzgado de Letras de Melipilla                 </option>
    <option value="377">1º Juzgado de Letras de Buin                      </option>
    <option value="378">2º Juzgado de Letras de Buin                      </option>
    <option value="388">Juzgado de Letras de Peñaflor                     </option>
    <option value="390">4º Juzgado Civil de San Miguel                    </option>
    <option value="400">1º Juzgado de Letras de San Bernardo              </option>
    <option value="401">2º Juzgado de Letras de San Bernardo              </option>
</select>
